# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vaidas Lungis - right here right now
description: > # this means to ignore newlines until "baseurl:"
  Personal site of Vaidas Lungis
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vaidas-lungis.github.io" # the base hostname & protocol for your site
github_username:  vaidas-lungis

# Build settings
markdown: kramdown
